### ISSUE TITLE
This plugin requiere IPv4.

### ISSUE THREAD

**Issue by valentin2105** [hbakkum/rundeck-hipchat-plugin#15]
Hi,

I'm using Rundeck in a IPv6 only machine and this awesome plugin won't work because it requiere visibly IPv4 connectivity.

Can you do something for me ? 

Thanks.

**Comment by hbakkum** [comment]
Hi there,

Thanks for raising this issue - are you able to send me the specific error you are seeing in the rundeck logs?

Cheers,
Hayden

**Comment by valentin2105** [comment]
Hey,

Here is the logs: 

```
INFO  ExecutionUtilService: Execution successful: 11 in project BaseProject
ERROR HipChatNotificationPlugin: Error sending HipChat notification to room: [#Citius]
com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPluginException: Error opening connection to HipChat URL: [Stream closed].
	at com.hbakkum.rundeck.plugins.hipchat.http.RestyHttpRequestExecutor.execute(RestyHttpRequestExecutor.java:44)
	at com.hbakkum.rundeck.plugins.hipchat.roomnotifier.HipChatApiVersion1RoomNotifier.invokeHipChatAPI(HipChatApiVersion1RoomNotifier.java:66)
	at com.hbakkum.rundeck.plugins.hipchat.roomnotifier.HipChatApiVersion1RoomNotifier.sendRoomNotification(HipChatApiVersion1RoomNotifier.java:49)
	at com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPlugin.sendRoomNotifications(HipChatNotificationPlugin.java:178)
	at com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPlugin.postNotification(HipChatNotificationPlugin.java:159)
	at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:490)
	at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:352)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:147)
	at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:89)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:86)
	at rundeck.services.ExecutionService$_saveExecutionState_closure61.doCall(ExecutionService.groovy:2367)
	at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2268)
	at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:511)
	at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:449)
	at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:521)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:164)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:91)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:90)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at us.monoid.web.AbstractResource.fill(AbstractResource.java:44)
	at us.monoid.web.Resty.fillResourceFromURL(Resty.java:432)
	at us.monoid.web.Resty.doGET(Resty.java:388)
	at us.monoid.web.Resty.text(Resty.java:241)
	at us.monoid.web.Resty.text(Resty.java:271)
	at com.hbakkum.rundeck.plugins.hipchat.http.RestyHttpRequestExecutor.execute(RestyHttpRequestExecutor.java:38)
	... 20 more
ERROR NotificationService: Notification Failed: HipChatNotification
```

As you'll see, Rundeck listen only in IPv6 : 

```
tcp6       0      0 :::4440                 :::*                    LISTEN      688/java
```

**Comment by hbakkum** [comment]
Hi,

Are you hosting your own hipchat server? Or are you using the webservice (i.e. https://api.hipchat.com)? Have you tested connectivity between your server hosting rundeck and hipchat?

Thanks,
Hayden

**Comment by Tokynet** [comment]
I'm going to comment here because i have a similar issue.

Details:
Self hosted hipchat
Network connectivity from rundeck to hipchat server (5222, 5223 and 443)

INFO  ExecutionUtilService: Execution successful: 53 in project Test
ERROR HipChatNotificationPlugin: Error sending HipChat notification to room: [1_automation@hipchat.MYDOMAIN.com]
com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPluginException: Error opening connection to HipChat URL: [Stream closed].
	at com.hbakkum.rundeck.plugins.hipchat.http.RestyHttpRequestExecutor.execute(RestyHttpRequestExecutor.java:44)
	at com.hbakkum.rundeck.plugins.hipchat.roomnotifier.HipChatApiVersion1RoomNotifier.invokeHipChatAPI(HipChatApiVersion1RoomNotifier.java:66)
	at com.hbakkum.rundeck.plugins.hipchat.roomnotifier.HipChatApiVersion1RoomNotifier.sendRoomNotification(HipChatApiVersion1RoomNotifier.java:49)
	at com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPlugin.sendRoomNotifications(HipChatNotificationPlugin.java:178)
	at com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPlugin.postNotification(HipChatNotificationPlugin.java:159)
	at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:490)
	at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:352)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:147)
	at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:89)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:86)
	at rundeck.services.ExecutionService$_saveExecutionState_closure61.doCall(ExecutionService.groovy:2367)
	at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2268)
	at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:511)
	at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:449)
	at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:521)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:164)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:91)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:90)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at us.monoid.web.AbstractResource.fill(AbstractResource.java:44)
	at us.monoid.web.Resty.fillResourceFromURL(Resty.java:432)
	at us.monoid.web.Resty.doGET(Resty.java:388)
	at us.monoid.web.Resty.text(Resty.java:241)
	at us.monoid.web.Resty.text(Resty.java:271)
	at com.hbakkum.rundeck.plugins.hipchat.http.RestyHttpRequestExecutor.execute(RestyHttpRequestExecutor.java:38)
	... 20 more
ERROR NotificationService: Notification Failed: HipChatNotification

I'm not sure if I have a issue with my hipchat setup, since the Conference (MUC) domain I see on the hipchat server interface is conf.btf.hipchat.com not sure if it should be @hipchat.MYDOMAIN.com.

Any help is greatly appreciated.

**Comment by hbakkum** [comment]
Hi,

So can I just confirm the following:

- you are running your own hipchat server
- you have configured your hipchat servers base url in either the rundeck framework or project properties, e.g.:
framework.plugin.Notification.HipChatNotification.hipchatServerBaseUrl=https\://yourhipchatserver.yourdomain
(see the user guide for more info: https://github.com/hbakkum/rundeck-hipchat-plugin/wiki/User-Guide)
- you have connectivity (i.e. you can make hipchat api requests) from your rundeck server to your hipchat server

Cheers,
Hayden

**Comment by valentin2105** [comment]
Hey @hbakkum ,

Sorry for the delay,

My IPv6 only server can reach correctly Hipchat's API who is only in IPv4 (but I use NAT64 for that). 

```
$ curl -vv https://api.hipchat.com/sign_in
< HTTP/1.1 200 OK
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Content-Type: text/html; charset=UTF-8
< Date: Fri, 14 Jul 2017 20:28:40 GMT
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
< Server: nginx
< Set-Cookie: s=522677a729333226691ad8b71e100573; expires=Fri, 28-Jul-2017 20:28:40 GMT; Max-Age=1209600; path=/; domain=hipchat.com; secure; HttpOnly
```

**Comment by valentin2105** [comment]
Have you tested it with Rundeck 2.8.x ? It seem make Rundeck bug a lot. 
When enable hipchat notification, the job never finish and I need to kill rundeck process to recover..

No logs about that.

**Comment by hbakkum** [comment]
Hi @valentin2105,

I have been using rundeck 2.8.2 with the plugin for a few months now with no problems. Are you using a more recent version than this?

Cheers,
Hayden
