### ISSUE TITLE
Hipchat SSL API V2 broken

### ISSUE THREAD

**Issue by jedblack** [hbakkum/rundeck-hipchat-plugin#8]
Do I need to add the hipchat upstream cert to the keystore in rundeck, we are flowing through a squid proxy for connectivity 

2015-01-23 13:04:09,236 [quartzScheduler_Worker-1] DEBUG freemarker.cache - Compiling FreeMarker template "hipchat-message.ftl"["en_US",UTF-8,parsed]  from "jar:file:/var/lib/rundeck/var/tmp/pluginJars/20150121111035000-rundeck-hipchat-plugin-1.5.0.jar!/templates/hipchat-message.ftl"
2015-01-23 13:04:09,268 [quartzScheduler_Worker-1] ERROR com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPlugin - Error sending HipChat notification to room: [669280]
com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPluginException: Error opening connection to HipChat URL: [sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target].
	at com.hbakkum.rundeck.plugins.hipchat.http.RestyHttpRequestExecutor.execute(RestyHttpRequestExecutor.java:67)
	at com.hbakkum.rundeck.plugins.hipchat.roomnotifier.HipChatApiVersion2RoomNotifier.sendRoomNotification(HipChatApiVersion2RoomNotifier.java:45)
	at com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPlugin.sendRoomNotifications(HipChatNotificationPlugin.java:158)
	at com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPlugin.postNotification(HipChatNotificationPlugin.java:139)
	at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:465)
	at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:327)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:142)
	at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:84)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:81)
	at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:1847)
	at rundeck.quartzjobs.ExecutionJob$_saveState_closure3.doCall(ExecutionJob.groovy:390)
	at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:343)
	at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:388)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:122)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:69)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:68)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:199)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:546)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at us.monoid.web.Content.addContent(Content.java:43)
	at us.monoid.web.Resty.doPOSTOrPUT(Resty.java:393)
	at us.monoid.web.Resty.text(Resty.java:258)
	at us.monoid.web.Resty.text(Resty.java:284)
	at com.hbakkum.rundeck.plugins.hipchat.http.RestyHttpRequestExecutor.execute(RestyHttpRequestExecutor.java:61)
	... 18 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	... 23 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)

**Comment by hbakkum** [comment]
Hi there,

Apologies for the late reply. Are you  connecting to the public Hipchat API or a locally hosted Hipchat server instance? If you are using he public API then you could check the sites CA cert is trusted by Java, that is, exists in cacerts (it should). If your using a Hipchat server and say, a self signed cert, then you would need to import this.

Cheers,
Hayden
