### ISSUE TITLE
Rundeck fails to connect to hipchat

### ISSUE THREAD

**Issue by orenmaor** [hbakkum/rundeck-hipchat-plugin#9]
2015-09-19 04:49:51,007 [quartzScheduler_Worker-2] ERROR grails.app.services.rundeck.services.NotificationService - Notification Failed: HipChatNotification
2015-09-19 04:49:55,346 [quartzScheduler_Worker-2] INFO  grails.app.services.rundeck.services.ExecutionUtilService - Execution successful: 334
2015-09-19 04:49:55,506 [quartzScheduler_Worker-2] ERROR com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPlugin - Error sending HipChat notification to room: [xxxx]
com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPluginException: Error opening connection to HipChat URL: [Stream closed].
	at com.hbakkum.rundeck.plugins.hipchat.http.RestyHttpRequestExecutor.execute(RestyHttpRequestExecutor.java:44)
	at com.hbakkum.rundeck.plugins.hipchat.roomnotifier.HipChatApiVersion1RoomNotifier.invokeHipChatAPI(HipChatApiVersion1RoomNotifier.java:64)
	at com.hbakkum.rundeck.plugins.hipchat.roomnotifier.HipChatApiVersion1RoomNotifier.sendRoomNotification(HipChatApiVersion1RoomNotifier.java:47)
	at com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPlugin.sendRoomNotifications(HipChatNotificationPlugin.java:158)
	at com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPlugin.postNotification(HipChatNotificationPlugin.java:139)
	at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:471)
	at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:333)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:142)
	at rundeck.services.NotificationService$_triggerJobNotification_closure1.doCall(NotificationService.groovy:84)
	at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:81)
	at rundeck.services.ExecutionService$_saveExecutionState_closure54.doCall(ExecutionService.groovy:1904)
	at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:1809)
	at rundeck.quartzjobs.ExecutionJob$_saveState_closure3.doCall(ExecutionJob.groovy:449)
	at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:392)
	at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:458)
	at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:143)
	at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:71)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:70)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:151)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at us.monoid.web.AbstractResource.fill(AbstractResource.java:44)
	at us.monoid.web.Resty.fillResourceFromURL(Resty.java:432)
	at us.monoid.web.Resty.doGET(Resty.java:388)
	at us.monoid.web.Resty.text(Resty.java:241)
	at us.monoid.web.Resty.text(Resty.java:271)
	at com.hbakkum.rundeck.plugins.hipchat.http.RestyHttpRequestExecutor.execute(RestyHttpRequestExecutor.java:38)
	... 20 more

**Comment by orenmaor** [comment]
I figured out how to fix this:
openssl s_client -showcerts -connect api.hipchat.com:443 </dev/null 2>/dev/null|openssl x509 -outform PEM >mycertfile.pem

keytool -import -file mycertfile.pem -alias CAAlias -keystore /etc/rundeck/ssl/truststore -storepass $(truststore_password)

**Comment by jquick** [comment]
Also for this to work you have to enable ssl for rundeck even if your not using https, this will load the ssl truststore and then it will work.
